// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJQzRi2jcDurPf83_xgmeUQygWZ78jXeE',
    appId: '1:556204564529:web:450e94c1e5f55f1262b510',
    messagingSenderId: '556204564529',
    projectId: 'lojaflutter-2a582',
    authDomain: 'lojaflutter-2a582.firebaseapp.com',
    databaseURL: 'https://lojaflutter-2a582-default-rtdb.firebaseio.com',
    storageBucket: 'lojaflutter-2a582.appspot.com',
    measurementId: 'G-FCNBRDNS6X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDxbBrlPRXJzRUkvcxxgQfE5pYSgh5odg',
    appId: '1:556204564529:android:f08c4183d6d5371f62b510',
    messagingSenderId: '556204564529',
    projectId: 'lojaflutter-2a582',
    databaseURL: 'https://lojaflutter-2a582-default-rtdb.firebaseio.com',
    storageBucket: 'lojaflutter-2a582.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdbjfn-GV8VwppJ-qg5lUo_jCix2dPkRc',
    appId: '1:556204564529:ios:53699caffa6c1a4862b510',
    messagingSenderId: '556204564529',
    projectId: 'lojaflutter-2a582',
    databaseURL: 'https://lojaflutter-2a582-default-rtdb.firebaseio.com',
    storageBucket: 'lojaflutter-2a582.appspot.com',
    iosClientId: '556204564529-atno2aqob3t0544v7642q422kb1v3nju.apps.googleusercontent.com',
    iosBundleId: 'br.com.erick.untitled9',
  );
}
